# -*- coding: utf-8 -*-
"""NYC_Airbnb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n_jOAd5H06wglT2xL-Q8Pbxy9j9OKtbw
"""

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas.api.types import CategoricalDtype

from google.colab import drive
drive.mount('/content/drive')

df_airbnb=pd.read_csv('/content/drive/MyDrive/airbnb.csv')
df_airbnb.head()

sns.set(rc={'figure.figsize':(6,4)})

df_airbnb.info()

df_airbnb.columns

df_airbnb["neighbourhood_group"].unique()

df_airbnb["neighbourhood_group"].value_counts()

df_airbnb["neighbourhood_group"].value_counts().plot.barh().set_title("Class Frequencies of Neighbourhood Variable")

df_airbnb.groupby("neighbourhood_group").sum().plot.pie(y="price", autopct="%.1f%%", ylabel="", legend=False, figsize=(5,5)).set_title("Graphic of Neighbourhood Group")

df_airbnb["room_type"].unique()

df_airbnb["room_type"].value_counts()

df_airbnb["room_type"].value_counts().plot.barh().set_title("Class Frequencies of Room Type Variable")

df_airbnb.groupby("room_type").sum().plot.pie(y="price", autopct="%.1f%%", ylabel="", legend=False, figsize=(5,5)).set_title("Graphic of Room Type")

sns.barplot(df_airbnb,x=df_airbnb['room_type'],y=df_airbnb.index,hue="neighbourhood_group").set_title("Graphic Of Room Type by Neighbourhood")
plt.ylabel("Number Of Room Type")
plt.legend(loc='upper center')

df_airbnb.describe()

sns.scatterplot(data=df_airbnb,y='neighbourhood_group',x="price", color="orange")
plt.title('Prices Of Neighbourhood Group')

sns.catplot(x="neighbourhood_group", y="price", data=df_airbnb, color="orange")
plt.title("Neighbourhood - Price")

sns.scatterplot(data=df_airbnb,y='room_type',x="price", color="orange")
plt.title('Prices Of Room Type')

sns.catplot(x="room_type", y="price", data=df_airbnb, color="orange")
plt.title("Room Type - Price")

sns.histplot(df_airbnb["price"], kde=True, color="orange") # bins= auto

sns.histplot(df_airbnb,x="price",kde=True, color="orange")
plt.axis([0,2500,0,3000])

sns.kdeplot(df_airbnb["price"], color="orange")
plt.axis([0,2000,0,0.006])

sns.catplot(x="room_type", y="price", hue="neighbourhood_group", kind="point", data=df_airbnb)
plt.title("Room Type - Price")

(sns.FacetGrid(df_airbnb, hue="room_type", height=5, xlim=(0, 1100)).map(sns.kdeplot, "price", shade=True).add_legend())

plt.title("Correlation Matrix")
sns.heatmap(df_airbnb.corr(), annot=True);

sns.pairplot(data=df_airbnb,markers='*')